name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 11]
    name: Java ${{ matrix.java-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Scala
      uses: olafurpg/setup-scala@v13
      with:
        java-version: "adopt@1.${{ matrix.java-version }}"
    - name: Build and Test
      run: sbt -v -Dfile.encoding=UTF-8 +test